app/app/urls.py
from django.urls import path
import django.contrib.auth.views as auth_views

from . import views

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "login/",
        views.login,
        name="login",
    ),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),
    path("create_note/", views.create_note, name="create_note"),
    path("delete_note/<int:pk>", views.delete_note, name="delete_note"),
    path("shared/", views.shared, name="shared"),
    path("add_friend/", views.add_friend, name="add_friend"),
]

app/flawedsite/urls.py
from django.urls import path, include

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

app/app/templates/app/add_friend.html
{% extends "app/base.html" %}
{% block body %}



<h1>Add friend</h1>

<h2>Friends</h2>

<ul>
    {% for friend in friends %}
        <li>{{ friend }}</li>
    {% endfor %}
</ul>

<h2>Users</h2>
    {% if users|length > 0%}
    <form action="{% url 'app:add_friend' %}" method="post">
        {% csrf_token %}
        <select name="username">
            {% for user in users %}
            <option value="{{ user.username }}">{{ user.username }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>
    {% else %}
        No users to add.
    {% endif %}
{% endblock body %}

app/app/templates/app/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <title>Flawed Site</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>

<body>
    <div id="menu-bar">
        {% if user.is_authenticated %}
        <div id="menu-bar-username">Logged in as {{ user.username }}</div>
        <a class="button" href="{% url 'app:logout' %}">Log out</a>
        <a class="button" href="{% url 'app:index' %}">Home</a>
        <a class="button" href="{% url 'app:add_friend' %}">Add friend</a>
        <a class="button" href="{% url 'app:shared' %}">Shared notes</a>
        {% else %}
        <a class="button" href="{% url 'app:login' %}">Login</a>
        <a class="button" href="{% url 'app:signup' %}">Sign Up</a>
        {% endif %}
    </div>
    {% block body %}
    {% endblock body %}
</body>

</html>

app/app/templates/app/index.html
{% extends "app/base.html" %}
{% block body %}

<h1>Notes View</h1>

<h2>Add note</h2>
<form method="POST" action="{% url 'app:create_note' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add note">
</form>

<h2>Notes</h2>
<div class="notes-list">
    <ul>
        {% for note in notes %}
        
        <!-- FLAW: Injection -->
        <!-- See index in views -->

        <!-- PROPER VERSION -->
        <!-- <li class="notes">{{ note.text|urlize }}</li> -->

        <!-- FLAWED VERSION -->
        <li class="notes">{{ note.text|join:" " }}</li>

        <form method="POST" action="{% url 'app:delete_note' pk=note.pk %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="/">
            <input type="submit" value="Delete">
        </form>
        {% endfor %}
    </ul>
</div>

{% endblock body %}

app/app/templates/app/login.html
{% extends "app/base.html" %}
{% block body %}
<!-- Just the baseline Django login form, slightly modified -->
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'app:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
    <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock body %}

app/app/templates/app/shared.html
{% extends "app/base.html" %}
{% block body %}

<h1>Shared Notes</h1>

<h2>Notes</h2>
{% for username, notes in others_notes %}
<h3>{{ username }}</h3>
<div class="notes-list">
    <ul>
        {% for note in notes %}
        <!-- Using the intentionally insecure url-ization result -->
        <li class="notes">{{ note.text|join:" " }}</li>
        {% endfor %}
    </ul>
</div>
{% endfor %}

{% endblock body %}

app/app/templates/app/signup.html
{% extends "app/base.html" %}

{% block body %}

<h1>Sign Up</h1>

{% if form.errors %}
<h2>Some issues were found in the details. Try again.</h2>
{% endif %}

<form method="post" action="{% url 'app:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="sign up">
</form>

{% endblock body %}